spring:
  application:
    name: Service-registry

server:
  port: 8761


management:
  endpoints:
    web:
      exposure:
        include:
  health:
    readiness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enable: true

eureka:
  instance:
    hostname: localhost
  #  below line restrics eureka server from register itself and restric from feching with other services.
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/