version: '3.8'

services:
  gateway_service:
    image: uday2626/gateway:v1
    ports:
      - "9091:9091"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    networks:
      - bank_network

networks:
  bank_network:
    driver: overlay
