spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://localhost:9092/"


  cloud:
    gateway:
      routes:
        - id: auth_route
          uri: http://authentication:9093
          predicates:
            - Path=/api/auth/**


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Bank Gateway Server Application"
    version: "1.0"

logging:
  level:
    com:
      bank:
        gatewayserver: DEBUG

server:
  port: 9091

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.1.100:8761/eureka
