version: '3.8'

services:
  eureka-server:
    image: uday2626/eureka-server:v1
    ports:
      - "8761:8761"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    networks:
      - bank_network

  gateway-service:
    image: uday2626/gateway:v1
    ports:
      - "9091:9091"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - bank_network

  authentication:
    image: uday2626/authentication:v1
    ports:
      - "9093:9093"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - bank_network

networks:
  bank_network:
    driver: overlay
