spring:
  application:
    name: "accounts"
  config:
    import: "optional:configserver:http://192.168.1.100:9092/"

  datasource:
    url: jdbc:mysql://192.168.1.100:3306/accounts
    username: bankuser
    password: numsbank
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml


info:
  app:
    name: "accounts"
    description: "Application for online banking accounts."
    version: "1.0"

server:
  port: 9095


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.1.100:8761/eureka