version: '3.8'

services:
  config_service:
    image: uday2626/configserver:v1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "9092:9092"
    networks:
      - bank_network

networks:
  bank_network:
    driver: overlay

