version: '3.8'

services:
  email_service:
    image: uday2626/transaction:v1
    ports:
      - "9096:9096"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    networks:
      - bank_network

networks:
  bank_network:
    driver: overlay